language: d

dist: xenial
sudo: required

before_install:
  - sudo add-apt-repository -y ppa:gertvdijk/opensc-backports
  - sudo apt-get update -y -qq
  - sudo apt-get install -y -qq opensc-pkcs11 opensc
  - sudo ln -s -T /usr/lib/x86_64-linux-gnu/libopensc.so.5.0.0 /usr/lib/libopensc.so
  - sudo ln -s -T /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so   /usr/lib/opensc-pkcs11.so
  - sudo ldconfig

install:
  - wget -O doveralls "https://github.com/ColdenCullen/doveralls/releases/download/v1.3.2/doveralls_linux_travis"
  - chmod +x doveralls

script:
  - dub test -b unittest-cov
  - ./doveralls
